In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('G:/SEM 5/mini-project/test_data.csv', header=0)

In [3]:
del dataset['SEM III Project Marks']
del dataset['SEM IV Project Marks']
del dataset['Number of Internships Completed/ Ongoing']
del dataset['Attendance']
del dataset['Member of any Student Chapter']
del dataset['Timestamp']


In [4]:
dataset['avg_GPA'] = (dataset.GPA_SEM_III +dataset.GP_SEM_IV)/2

In [5]:
dataset

Applied Mathematics - III  Applied Mathematics - IV  \
0                           94                        93   
1                           90                        79   
2                           19                        71   
3                           71                        69   
4                           64                        80   
..                         ...                       ...   
110                         39                        32   
111                         30                        49   
112                         55                        68   
113                         31                        19   
114                         47                        47   

     Discrete Structure and Graph Theory  Data Structures  \
0                                     82               70   
1                                     64               80   
2                                     48               40   
3                                     62               54   
4                                     62               43   
..                                   ...              ...   
110                                   43               36   
111                                   51               40   
112                                   66               64   
113                                   50               44   
114                                   43               42   

     Analysis Of Algorithm  Skill Based Lab (Java)  Skill Based Lab (Python)  \
0                       86                      47                        46   
1                       70                      46                        37   
2                       49                      42                        35   
3                       65                      46                        38   
4                       69                      45                        32   
..                     ...                     ...                       ...   
110                     46                      47                        38   
111                     46                      46                        37   
112                     66                      45                        46   
113                     47                      45                        30   
114                     55                      45                        35   

     GPA_SEM_III  GP_SEM_IV  avg_GPA  
0           9.08       9.56    9.320  
1           8.77       8.52    8.645  
2           0.00       7.00    3.500  
3           7.31       8.07    7.690  
4           6.96       8.00    7.480  
..           ...        ...      ...  
110         0.00       0.00    0.000  
111         0.00       6.85    3.425  
112         7.08       7.52    7.300  
113         0.00       0.00    0.000  
114         0.00       6.93    3.465  

[115 rows x 10 columns]

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
y = dataset.iloc[:, -1].values

In [18]:
y

array([ 9.32,  8.64,  3.5 ,  7.69,  7.48,  7.41,  9.38,  9.65,  9.15,
        3.28,  9.14,  7.82,  3.56,  7.79,  7.02,  8.7 ,  7.65,  9.38,
       10.  ,  7.52,  9.11,  7.68,  8.62,  7.12,  3.65,  9.14,  8.69,
        8.97,  4.04,  7.17,  8.64,  8.28,  8.6 ,  7.87,  2.92,  9.45,
        8.34,  9.3 ,  7.36,  7.99,  6.18,  7.12,  8.68,  8.84,  8.74,
        6.97,  7.25,  9.31,  8.2 ,  4.13,  6.98,  8.26,  3.4 ,  8.79,
        8.98,  8.77,  7.14,  9.13,  3.77,  7.58,  9.29,  8.11,  8.08,
        3.17,  7.21,  9.12,  7.28,  8.35,  7.47,  7.92,  0.  ,  9.3 ,
        7.98,  3.04,  8.38,  8.88,  0.  ,  7.22,  9.38,  6.52,  9.55,
        6.28,  6.75,  8.37,  8.29,  6.92,  6.87,  9.18,  8.5 ,  7.42,
        8.77,  7.05,  7.26,  9.12,  7.55,  7.99,  6.08,  8.72,  6.94,
        0.  ,  7.21,  7.38,  8.  ,  7.63,  5.54,  6.84,  3.35,  2.89,
        6.14,  0.  ,  0.  ,  3.42,  7.3 ,  0.  ,  3.46])

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
X_train

array([[58.  , 84.  , 55.  , 37.  , 61.  , 43.  , 40.  ,  5.85,  8.  ],
       [86.  , 94.  , 74.  , 85.  , 81.  , 43.  , 43.  ,  9.23,  9.37],
       [57.  , 53.  , 60.  , 55.  , 65.  , 36.  , 40.  ,  6.62,  7.11],
       [39.  , 32.  , 43.  , 36.  , 46.  , 47.  , 38.  ,  0.  ,  0.  ],
       [21.  , 25.  , 49.  , 31.  , 31.  , 45.  , 40.  ,  0.  ,  0.  ],
       [83.  , 81.  , 89.  , 66.  , 77.  , 42.  , 35.  ,  9.08,  9.22],
       [62.  , 71.  , 60.  , 40.  , 68.  , 42.  , 37.  ,  6.27,  8.26],
       [73.  , 78.  , 50.  , 63.  , 84.  , 37.  , 36.  ,  7.38,  8.36],
       [65.  , 64.  , 55.  , 56.  , 57.  , 43.  , 44.  ,  6.5 ,  7.44],
       [71.  , 69.  , 62.  , 54.  , 65.  , 46.  , 38.  ,  7.31,  8.07],
       [77.  , 81.  , 56.  , 57.  , 75.  , 45.  , 43.  ,  7.5 ,  8.89],
       [96.  , 94.  , 88.  , 78.  , 71.  , 45.  , 47.  ,  9.54,  9.21],
       [78.  , 94.  , 79.  , 73.  , 84.  , 42.  , 37.  ,  8.42,  9.54],
       [47.  , 47.  , 43.  , 42.  , 55.  , 45.  , 35.  ,  0.  , 

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[9.14 9.14]
 [8.38 8.38]
 [7.28 7.28]
 [8.26 8.26]
 [9.66 9.65]
 [9.38 9.38]
 [7.06 7.05]
 [7.43 7.42]
 [3.35 3.35]
 [8.08 8.08]
 [8.65 8.64]
 [3.5  3.5 ]
 [9.13 9.12]
 [8.62 8.62]
 [8.84 8.84]
 [2.89 2.89]
 [3.65 3.65]
 [3.04 3.04]
 [9.29 9.29]
 [7.15 7.14]
 [7.66 7.65]
 [7.79 7.79]
 [8.69 8.69]]


In [11]:
X_test

array([[96.  , 82.  , 69.  , 84.  , 65.  , 45.  , 43.  ,  8.92,  9.36],
       [58.  , 85.  , 64.  , 57.  , 83.  , 44.  , 43.  ,  7.08,  9.67],
       [59.  , 73.  , 62.  , 73.  , 61.  , 44.  , 40.  ,  7.23,  7.33],
       [75.  , 79.  , 51.  , 66.  , 78.  , 40.  , 39.  ,  7.42,  9.1 ],
       [90.  , 92.  , 87.  , 85.  , 81.  , 46.  , 40.  ,  9.54,  9.77],
       [75.  , 96.  , 78.  , 81.  , 78.  , 43.  , 44.  ,  9.05,  9.7 ],
       [70.  , 59.  , 65.  , 56.  , 48.  , 42.  , 39.  ,  7.31,  6.8 ],
       [60.  , 64.  , 60.  , 64.  , 73.  , 44.  , 39.  ,  6.96,  7.89],
       [45.  , 41.  , 47.  , 41.  , 56.  , 43.  , 37.  ,  0.  ,  6.7 ],
       [73.  , 83.  , 71.  , 52.  , 87.  , 41.  , 41.  ,  7.27,  8.89],
       [84.  , 81.  , 76.  , 70.  , 91.  , 36.  , 40.  ,  8.48,  8.81],
       [19.  , 71.  , 48.  , 40.  , 49.  , 42.  , 35.  ,  0.  ,  7.  ],
       [85.  , 79.  , 81.  , 71.  , 83.  , 43.  , 40.  ,  8.62,  9.63],
       [84.  , 84.  , 71.  , 70.  , 82.  , 47.  , 40.  ,  8.62, 

In [15]:
global a
a = regressor.predict([[50.  , 82.  , 69.  , 84.  , 65.  , 45.  , 43.  ,  8.92,  9.36]])
print(a)

[9.14]


In [13]:
def check():
    if(a == 9.14):
        print('you good')