##  Classification 

In [1]:
import numpy as np
import pandas as pd
# import seaborn as sns

In [2]:
# df = pd.read_csv('G:/SEM 5/mini-project/dataset-new/cluster.csv', header=0)
df = pd.read_csv('G:/SEM 5/mini-project/code new/clustering/cluster.csv', header=0)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 327 entries, 0 to 326
Data columns (total 42 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    327 non-null    int64  
 1    AM_SE        327 non-null    int64  
 2   AM_IA         327 non-null    int64  
 3   DLDA_SE       327 non-null    int64  
 4   DLDA_IA       327 non-null    int64  
 5   DSGT_SE       327 non-null    int64  
 6   DSGT_IA       327 non-null    int64  
 7   ECCF_SE       327 non-null    int64  
 8   ECCF_IA       327 non-null    int64  
 9   DS_SE         327 non-null    int64  
 10  DS_IA         327 non-null    int64  
 11  DigitalSL_TW  327 non-null    int64  
 12  DSL_OP        327 non-null    int64  
 13  BE_TW         327 non-null    int64  
 14  BE_OP         327 non-null    int64  
 15  DataSL_TW     327 non-null    int64  
 16  DSL_OP.1      327 non-null    int64  
 17  OOPM_TW       327 non-null    int64  
 18  OOPM_OP       327 non-null    

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
y = df['cluster'].values
y
X = df.values
X = np.delete(X,41,axis=1)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=0)

##  Decision tree

In [7]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [8]:
y_pred = classifier.predict(X_test) 

In [9]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [10]:
cm

array([[19,  0,  3,  3,  0,  1],
       [ 0,  8,  0,  0,  4,  3],
       [ 2,  3,  7,  3,  0,  3],
       [ 3,  0,  0, 12,  0,  0],
       [ 0,  4,  0,  0,  8,  0],
       [ 2,  1,  2,  0,  0, 17]], dtype=int64)

In [11]:
classifier.score(X_test, y_test)

0.6574074074074074

## K nearest neighbour

In [12]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(X_train, y_train)  

KNeighborsClassifier()

In [13]:
y_pred = classifier.predict(X_test)  

In [14]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [15]:
cm

array([[22,  0,  2,  2,  0,  0],
       [ 0, 14,  0,  0,  0,  1],
       [ 3,  0, 14,  0,  0,  1],
       [ 5,  0,  0, 10,  0,  0],
       [ 0,  7,  0,  0,  5,  0],
       [ 2,  2,  2,  0,  0, 16]], dtype=int64)

In [16]:
classifier.score(X_test, y_test)

0.75

## Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(X_train, y_train)  

GaussianNB()

In [18]:
y_pred = classifier.predict(X_test)  

In [19]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [20]:
cm

array([[22,  0,  3,  1,  0,  0],
       [ 0, 10,  0,  0,  2,  3],
       [ 3,  0, 14,  0,  0,  1],
       [ 2,  0,  0, 13,  0,  0],
       [ 0,  3,  0,  0,  9,  0],
       [ 2,  3,  0,  0,  0, 17]], dtype=int64)

In [21]:
classifier.score(X_test, y_test)

0.7870370370370371

## Support Vector classifier

In [22]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train, y_train)  

SVC(kernel='linear', random_state=0)

In [23]:
y_pred = classifier.predict(X_test)

In [24]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[25,  0,  1,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  2],
       [ 2,  1, 15,  0,  0,  0],
       [ 0,  0,  0, 15,  0,  0],
       [ 0,  2,  0,  0, 10,  0],
       [ 1,  1,  0,  0,  0, 20]], dtype=int64)

In [26]:
classifier.score(X_test, y_test)

0.9074074074074074

## Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression(random_state=0)  
classifier.fit(X_train, y_train) 

c:\users\shardul\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [28]:
y_pred = classifier.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)

In [30]:
cm

array([[21,  0,  1,  1,  0,  3],
       [ 1,  8,  2,  0,  1,  3],
       [ 4,  0, 13,  0,  0,  1],
       [ 5,  0,  0, 10,  0,  0],
       [ 0,  1,  0,  0, 10,  1],
       [ 3,  4,  0,  0,  0, 15]], dtype=int64)

In [31]:
classifier.score(X_test, y_test)

0.7129629629629629

## Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)

In [34]:
cm

array([[24,  0,  1,  1,  0,  0],
       [ 0, 14,  0,  0,  0,  1],
       [ 2,  0, 14,  1,  0,  1],
       [ 1,  0,  0, 14,  0,  0],
       [ 0,  4,  0,  0,  8,  0],
       [ 1,  0,  0,  0,  0, 21]], dtype=int64)

In [35]:
classifier.score(X_test, y_test)

0.8796296296296297

## SGD

In [36]:
from sklearn import linear_model

classifier = linear_model.SGDClassifier(max_iter = 1000, tol=1e-3,penalty = "elasticnet")
classifier.fit(X_train, y_train)

SGDClassifier(penalty='elasticnet')

In [37]:
y_pred=classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)

In [39]:
cm

array([[21,  0,  5,  0,  0,  0],
       [ 2,  6,  6,  0,  0,  1],
       [ 1,  3, 14,  0,  0,  0],
       [ 6,  0,  4,  5,  0,  0],
       [ 0,  4,  1,  0,  6,  1],
       [ 7,  8,  3,  0,  0,  4]], dtype=int64)

In [40]:
classifier.score(X_test, y_test)

0.5185185185185185